name: Delvelin by @hangga
description: Code Vulnerability Analyzer for Java and Kotlin.
url: https://delvelin.github.io
permalink: pretty
sass:
  style: compressed
version: 4.0.0
og_image: https://raw.githubusercontent.com/mdo/code-guide/gh-pages/code-guide-social.png
