title: Delvelin
description: Code Vulnerability Analyzer for Java and Kotlin.
include:
  - _headers
  - _redirects
kramdown:
  toc_levels: "2"
url: https://thelounge.chat # Domain used by jekyll-sitemap in sitemap.xml
plugins:
  - jekyll-sitemap
permalink: /:path
collections:
  docs:
    output: true
  api:
    output: true
    permalink: /docs/:collection/:path
  guides:
    output: true
    permalink: /docs/:collection/:path
