title: Delvelin
description: Delvelin is Code Vulnerability Analyzer for Java/Kotlin
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

baseurl: ""
url: "https://delvelin.github.io"
permalink: pretty